### ISSUE TITLE
Error on make up

### ISSUE THREAD

**Issue by gastoncs** [hgraca/explicit-architecture-php#24]
When I run  make up I get this error

> Step 1/4 : FROM hgraca/explicit-architecture:app.sfn.dev
ERROR: Service 'app' failed to build: manifest for hgraca/explicit-architecture:app.sfn.dev not found: manifest unknown: manifest unknown

Do I need to download the image first? if so there is an issue with image in https://hub.docker.com/r/hgraca/explicit-architecture

**Comment by hgraca** [comment]
Hi,

Yes, that's possible.
I haven't maintained this in quite some time.
I will try to have a look later this week.

Tkx for the heads up.

**Comment by hgraca** [comment]
I've pushed some commits and updated the readme, some steps are not automated.

I tested this, but if it still doesn't work for you, let me know.

**Comment by gastoncs** [comment]
Thank you very much Ill check it out!
